### ISSUE TITLE
about use_weight

### ISSUE THREAD

**Issue by za-wa-n-go** [lldacing/ComfyUI_BiRefNet_ll#5]
When executing with `use_weight` set to ON and placing the model in the same location as the BiRefNet model, the following error occurs.

```
!!! Exception during processing !!! 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 564, in _check_seekable
    f.seek(f.tell())
    ^^^^^^
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 142, in load_model
    biRefNet_model = BiRefNet(bb_pretrained=use_weight, bb_index=bb_index)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnet\models\birefnet.py", line 21, in __init__
    self.bb = build_backbone(self.config.bb, pretrained=bb_pretrained)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnet\models\backbones\build_backbone.py", line 26, in build_backbone
    bb = load_weights(bb, bb_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnet\models\backbones\build_backbone.py", line 31, in load_weights
    save_model = torch.load(config.weights[model_name], map_location='cpu')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 473, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 458, in __init__
    _check_seekable(buffer)
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 567, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 560, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```

**Comment by za-wa-n-go** [comment]
After restarting and executing, the error disappeared. My apologies.
