### ISSUE TITLE
Lite和Lite_2k报错

### ISSUE THREAD

**Issue by petercham** [lldacing/ComfyUI_BiRefNet_ll#8]
!!! Exception during processing !!! Error(s) in loading state_dict for BiRefNet:
        Missing key(s) in state_dict: "bb.layers.2.blocks.6.norm1.weight", "bb.layers.2.blocks.6.norm1.bias", "bb.layers.2.blocks.6.attn.relative_position_bias_table", "bb.layers.2.blocks.6.attn.relative_position_index", "bb.layers.2.blocks.6.attn.qkv.weight", "bb.layers.2.blocks.6.attn.qkv.bias", "bb.layers.2.blocks.6.attn.proj.weight", "bb.layers.2.blocks.6.attn.proj.bias", "bb.layers.2.blocks.6.norm2.weight", "bb.layers.2.blocks.6.norm2.bias", "bb.layers.2.blocks.6.mlp.fc1.weight", "bb.layers.2.blocks.6.mlp.fc1.bias", "bb.layers.2.blocks.6.mlp.fc2.weight", "bb.layers.2.blocks.6.mlp.fc2.bias", "bb.layers.2.blocks.7.norm1.weight", "bb.layers.2.blocks.7.norm1.bias", "bb.layers.2.blocks.7.attn.relative_position_bias_table", "bb.layers.2.blocks.7.attn.relative_position_index", "bb.layers.2.blocks.7.attn.qkv.weight", "bb.layers.2.blocks.7.attn.qkv.bias", "bb.layers.2.blocks.7.attn.proj.weight", "bb.layers.2.blocks.7.attn.proj.bias", "bb.layers.2.blocks.7.norm2.weight", "bb.layers.2.blocks.7.norm2.bias", "bb.layers.2.blocks.7.mlp.fc1.weight", "bb.layers.2.blocks.7.mlp.fc1.bias", "bb.layers.2.blocks.7.mlp.fc2.weight", "bb.layers.2.blocks.7.mlp.fc2.bias", "bb.layers.2.blocks.8.norm1.weight", "bb.layers.2.blocks.8.norm1.bias", "bb.layers.2.blocks.8.attn.relative_position_bias_table", "bb.layers.2.blocks.8.attn.relative_position_index", "bb.layers.2.blocks.8.attn.qkv.weight", "bb.layers.2.blocks.8.attn.qkv.bias", "bb.layers.2.blocks.8.attn.proj.weight", "bb.layers.2.blocks.8.attn.proj.bias", "bb.layers.2.blocks.8.norm2.weight", "bb.layers.2.blocks.8.norm2.bias", "bb.layers.2.blocks.8.mlp.fc1.weight", "bb.layers.2.blocks.8.mlp.fc1.bias", "bb.layers.2.blocks.8.mlp.fc2.weight", "bb.layers.2.blocks.8.mlp.fc2.bias", "bb.layers.2.blocks.9.norm1.weight", "bb.layers.2.blocks.9.norm1.bias", "bb.layers.2.blocks.9.attn.relative_position_bias_table", "bb.layers.2.blocks.9.attn.relative_position_index", "bb.layers.2.blocks.9.attn.qkv.weight", "bb.layers.2.blocks.9.attn.qkv.bias", "bb.layers.2.blocks.9.attn.proj.weight", "bb.layers.2.blocks.9.attn.proj.bias", "bb.layers.2.blocks.9.norm2.weight", "bb.layers.2.blocks.9.norm2.bias", "bb.layers.2.blocks.9.mlp.fc1.weight", "bb.layers.2.blocks.9.mlp.fc1.bias", "bb.layers.2.blocks.9.mlp.fc2.weight", "bb.layers.2.blocks.9.mlp.fc2.bias", "bb.layers.2.blocks.10.norm1.weight", "bb.layers.2.blocks.10.norm1.bias", "bb.layers.2.blocks.10.attn.relative_position_bias_table", "bb.layers.2.blocks.10.attn.relative_position_index", "bb.layers.2.blocks.10.attn.qkv.weight", "bb.layers.2.blocks.10.attn.qkv.bias", "bb.layers.2.blocks.10.attn.proj.weight", "bb.layers.2.blocks.10.attn.proj.bias", "bb.layers.2.blocks.10.norm2.weight", "bb.layers.2.blocks.10.norm2.bias", "bb.layers.2.blocks.10.mlp.fc1.weight", "bb.layers.2.blocks.10.mlp.fc1.bias", "bb.layers.2.blocks.10.mlp.fc2.weight", "bb.layers.2.blocks.10.mlp.fc2.bias", "bb.layers.2.blocks.11.norm1.weight", "bb.layers.2.blocks.11.norm1.bias", "bb.layers.2.blocks.11.attn.relative_position_bias_table", "bb.layers.2.blocks.11.attn.relative_position_index", "bb.layers.2.blocks.11.attn.qkv.weight", "bb.layers.2.blocks.11.attn.qkv.bias", "bb.layers.2.blocks.11.attn.proj.weight", "bb.layers.2.blocks.11.attn.proj.bias", "bb.layers.2.blocks.11.norm2.weight", "bb.layers.2.blocks.11.norm2.bias", "bb.layers.2.blocks.11.mlp.fc1.weight", "bb.layers.2.blocks.11.mlp.fc1.bias", "bb.layers.2.blocks.11.mlp.fc2.weight", "bb.layers.2.blocks.11.mlp.fc2.bias", "bb.layers.2.blocks.12.norm1.weight", "bb.layers.2.blocks.12.norm1.bias", "bb.layers.2.blocks.12.attn.relative_position_bias_table", "bb.layers.2.blocks.12.attn.relative_position_index", "bb.layers.2.blocks.12.attn.qkv.weight", "bb.layers.2.blocks.12.attn.qkv.bias", "bb.layers.2.blocks.12.attn.proj.weight", "bb.layers.2.blocks.12.attn.proj.bias", "bb.layers.2.blocks.12.norm2.weight", "bb.layers.2.blocks.12.norm2.bias", "bb.layers.2.blocks.12.mlp.fc1.weight", "bb.layers.2.blocks.12.mlp.fc1.bias", "bb.layers.2.blocks.12.mlp.fc2.weight", "bb.layers.2.blocks.12.mlp.fc2.bias", "bb.layers.2.blocks.13.norm1.weight", "bb.layers.2.blocks.13.norm1.bias", "bb.layers.2.blocks.13.attn.relative_position_bias_table", "bb.layers.2.blocks.13.attn.relative_position_index", "bb.layers.2.blocks.13.attn.qkv.weight", "bb.layers.2.blocks.13.attn.qkv.bias", "bb.layers.2.blocks.13.attn.proj.weight", "bb.layers.2.blocks.13.attn.proj.bias", "bb.layers.2.blocks.13.norm2.weight", "bb.layers.2.blocks.13.norm2.bias", "bb.layers.2.blocks.13.mlp.fc1.weight", "bb.layers.2.blocks.13.mlp.fc1.bias", "bb.layers.2.blocks.13.mlp.fc2.weight", "bb.layers.2.blocks.13.mlp.fc2.bias", "bb.layers.2.blocks.14.norm1.weight", "bb.layers.2.blocks.14.norm1.bias", "bb.layers.2.blocks.14.attn.relative_position_bias_table", "bb.layers.2.blocks.14.attn.relative_position_index", "bb.layers.2.blocks.14.attn.qkv.weight", "bb.layers.2.blocks.14.attn.qkv.bias", "bb.layers.2.blocks.14.attn.proj.weight", "bb.layers.2.blocks.14.attn.proj.bias", "bb.layers.2.blocks.14.norm2.weight", "bb.layers.2.blocks.14.norm2.bias", "bb.layers.2.blocks.14.mlp.fc1.weight", "bb.layers.2.blocks.14.mlp.fc1.bias", "bb.layers.2.blocks.14.mlp.fc2.weight", "bb.layers.2.blocks.14.mlp.fc2.bias", "bb.layers.2.blocks.15.norm1.weight", "bb.layers.2.blocks.15.norm1.bias", "bb.layers.2.blocks.15.attn.relative_position_bias_table", "bb.layers.2.blocks.15.attn.relative_position_index", "bb.layers.2.blocks.15.attn.qkv.weight", "bb.layers.2.blocks.15.attn.qkv.bias", "bb.layers.2.blocks.15.attn.proj.weight", "bb.layers.2.blocks.15.attn.proj.bias", "bb.layers.2.blocks.15.norm2.weight", "bb.layers.2.blocks.15.norm2.bias", "bb.layers.2.blocks.15.mlp.fc1.weight", "bb.layers.2.blocks.15.mlp.fc1.bias", "bb.layers.2.blocks.15.mlp.fc2.weight", "bb.layers.2.blocks.15.mlp.fc2.bias", "bb.layers.2.blocks.16.norm1.weight", "bb.layers.2.blocks.16.norm1.bias", "bb.layers.2.blocks.16.attn.relative_position_bias_table", "bb.layers.2.blocks.16.attn.relative_position_index", "bb.layers.2.blocks.16.attn.qkv.weight", "bb.layers.2.blocks.16.attn.qkv.bias", "bb.layers.2.blocks.16.attn.proj.weight", "bb.layers.2.blocks.16.attn.proj.bias", "bb.layers.2.blocks.16.norm2.weight", "bb.layers.2.blocks.16.norm2.bias", "bb.layers.2.blocks.16.mlp.fc1.weight", "bb.layers.2.blocks.16.mlp.fc1.bias", "bb.layers.2.blocks.16.mlp.fc2.weight", "bb.layers.2.blocks.16.mlp.fc2.bias", "bb.layers.2.blocks.17.norm1.weight", "bb.layers.2.blocks.17.norm1.bias", "bb.layers.2.blocks.17.attn.relative_position_bias_table", "bb.layers.2.blocks.17.attn.relative_position_index", "bb.layers.2.blocks.17.attn.qkv.weight", "bb.layers.2.blocks.17.attn.qkv.bias", "bb.layers.2.blocks.17.attn.proj.weight", "bb.layers.2.blocks.17.attn.proj.bias", "bb.layers.2.blocks.17.norm2.weight", "bb.layers.2.blocks.17.norm2.bias", "bb.layers.2.blocks.17.mlp.fc1.weight", "bb.layers.2.blocks.17.mlp.fc1.bias", "bb.layers.2.blocks.17.mlp.fc2.weight", "bb.layers.2.blocks.17.mlp.fc2.bias".

……

Traceback (most recent call last):
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 157, in load_model
    biRefNet_model.load_state_dict(state_dict)
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BiRefNet:

**Comment by petercham** [comment]
weight == True 报错：

!!! Exception during processing !!! 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
Traceback (most recent call last):
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\serialization.py", line 540, in _check_seekable
    f.seek(f.tell())
    ^^^^^^
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 144, in load_model
    biRefNet_model = BiRefNet(bb_pretrained=use_weight, bb_index=bb_index)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnet\models\birefnet.py", line 35, in __init__
    self.bb = build_backbone(self.config.bb, pretrained=bb_pretrained)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnet\models\backbones\build_backbone.py", line 25, in build_backbone
    bb = load_weights(bb, bb_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnet\models\backbones\build_backbone.py", line 29, in load_weights
    save_model = torch.load(config.weights[model_name], map_location='cpu', weights_only=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\serialization.py", line 449, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\serialization.py", line 434, in __init__
    _check_seekable(buffer)
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\serialization.py", line 543, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\serialization.py", line 536, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
